import WindowProvider from '../posts/Context/WindowContext';

export const metadata = {
  title: "Posts",
  description: "Generated by MiwaBox.live",
  icons: {
    icon: '/miwabox_icon.svg',
  },
};

export default function RootLayout({ children }) {
  return (
    <WindowProvider>
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/thinline.css"/>
        <main>{children}</main>
    </WindowProvider>
  );
}
