import { Analytics } from "@vercel/analytics/react"
import NextTopLoader from 'nextjs-toploader';

import './css/globalRes.css'
import './css/global.css'

import './css/Dialog/Dialog.css'
import './css/Dialog/DialogRes.css'
import './css/Dialog/Modal.css'
import './css/Dialog/ModalRes.css'

import './css/DropDown.css'
import './css/LoadMore.css'
import './css/ImageViewer.css'


export const metadata = {
  title: "MiwaBox",
  description: "Generated by MiwaBox.live",
  icons: {
    icon: '/miwabox_icon.svg',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <head>
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
          <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
        </head>
        <body>
          <NextTopLoader
            showSpinner={false}
            zIndex={1600}
            color="rgb(112, 174, 255)"
            speed={999}
          />
          <main>{children}</main>
        </body>
    </html>
  );
}
