import "../Lang/css/listword.css"
import "../Lang/css/listwordRes.css"
import "../Lang/css/listswitchselection.css"
import "../Lang/css/navbottom.css"
import "../Lang/css/main.css"
import SettingProvider from "../Lang/Context/SettingContext"

export const metadata = {
  title: "Mi 5000",
  description: "Generated by MiwaBox.live",
  icons: {
    icon: '/miwabox_icon.svg',
  },
};

export default function EnLangLayout({ children }) {
  return (
    <SettingProvider>
      <div>{children}</div>
    </SettingProvider>
  );
}